In [1]:
pip install kaggle

Requirement already satisfied: kaggle in /usr/local/lib/python3.7/dist-packages (1.5.12)
Requirement already satisfied: six>=1.10 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.15.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.7/dist-packages (from kaggle) (2021.10.8)
Requirement already satisfied: tqdm in /usr/local/lib/python3.7/dist-packages (from kaggle) (4.62.3)
Requirement already satisfied: urllib3 in /usr/local/lib/python3.7/dist-packages (from kaggle) (1.24.3)
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.23.0)
Requirement already satisfied: python-slugify in /usr/local/lib/python3.7/dist-packages (from kaggle) (5.0.2)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/dist-packages (from kaggle) (2.8.2)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.7/dist-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->kaggle) (2.10)

In [2]:
!mkdir ~/.kaggle

mkdir: cannot create directory ‘/root/.kaggle’: File exists

In [3]:
! cp kaggle.json ~/.kaggle/

In [4]:
! chmod 600 ~/.kaggle/kaggle.json

In [5]:
! kaggle competitions download web-traffic-time-series-forecasting

Warning: Looks like you're using an outdated API Version, please consider updating (server 1.5.12 / client 1.5.4)
train_1.csv.zip: Skipping, found more recently modified local copy (use --force to force download)
key_2.csv.zip: Skipping, found more recently modified local copy (use --force to force download)
key_1.csv.zip: Skipping, found more recently modified local copy (use --force to force download)
sample_submission_1.csv.zip: Skipping, found more recently modified local copy (use --force to force download)
train_2.csv.zip: Skipping, found more recently modified local copy (use --force to force download)
sample_submission_2.csv.zip: Skipping, found more recently modified local copy (use --force to force download)

In [6]:
! unzip key_1.csv.zip
! unzip key_2.csv.zip
! unzip train_1.csv.zip
! unzip train_2.csv.zip

Archive:  key_1.csv.zip
replace key_1.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: Archive:  key_2.csv.zip
replace key_2.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: Archive:  train_1.csv.zip
replace train_1.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: Archive:  train_2.csv.zip
replace train_2.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename:

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
train = pd.read_csv('/content/train_1.csv')

In [9]:
train.head()

                                                Page  ...  2016-12-31
0            2NE1_zh.wikipedia.org_all-access_spider  ...        20.0
1             2PM_zh.wikipedia.org_all-access_spider  ...        20.0
2              3C_zh.wikipedia.org_all-access_spider  ...        17.0
3         4minute_zh.wikipedia.org_all-access_spider  ...        11.0
4  52_Hz_I_Love_You_zh.wikipedia.org_all-access_s...  ...        10.0

[5 rows x 551 columns]

In [10]:
train = train.drop(["Page"],axis=1)

In [11]:
train

        2015-07-01  2015-07-02  2015-07-03  ...  2016-12-29  2016-12-30  2016-12-31
0             18.0        11.0         5.0  ...        19.0        18.0        20.0
1             11.0        14.0        15.0  ...        45.0        26.0        20.0
2              1.0         0.0         1.0  ...         3.0         4.0        17.0
3             35.0        13.0        10.0  ...        19.0        10.0        11.0
4              NaN         NaN         NaN  ...        13.0        36.0        10.0
...            ...         ...         ...  ...         ...         ...         ...
145058         NaN         NaN         NaN  ...         3.0         5.0        10.0
145059         NaN         NaN         NaN  ...         NaN         NaN         NaN
145060         NaN         NaN         NaN  ...         NaN         NaN         NaN
145061         NaN         NaN         NaN  ...         NaN         NaN         NaN
145062         NaN         NaN         NaN  ...         NaN         NaN         NaN

[145063 rows x 550 columns]

In [12]:
row = train.iloc[1,:].values

In [13]:
row

array([ 11.,  14.,  15.,  18.,  11.,  13.,  22.,  11.,  10.,   4.,  41.,
        65.,  57.,  38.,  20.,  62.,  44.,  15.,  10.,  47.,  24.,  17.,
        22.,   9.,  39.,  13.,  11.,  12.,  21.,  19.,   9.,  15.,  33.,
         8.,   8.,   7.,  13.,   2.,  23.,  12.,  27.,  27.,  36.,  23.,
        58.,  80.,  60.,  69.,  42., 161.,  94.,  77.,  78.,  20.,  24.,
        13.,  14.,  26.,   8.,  82.,  22.,  11.,  81.,  37.,   9.,  40.,
        47.,  18.,  23.,   6.,   2.,   7.,  16.,  10.,  34.,  14.,  31.,
        20.,  23.,  14.,  16.,  34.,  15.,  30.,  13.,  30.,  15.,  25.,
        17.,   8.,  12.,  17.,  10.,  21.,  18.,  30.,  13.,   7.,  15.,
        23.,  20.,  15.,   9.,  47.,  14.,  11.,  16.,  12.,   7.,  15.,
        14.,  12.,  18.,  29.,  39.,  11.,  14.,  28.,  17.,  20.,  17.,
        36.,  13.,  11.,  14.,  14.,  14.,  33.,  14.,  13.,  18.,  13.,
        11.,   8.,  10.,  11.,  81.,  14.,  20.,   6.,  16.,  18.,   9.,
        12.,  10.,   8.,  11.,  14.,  47.,  13.,  13.,   6.,  10.,   8.,
         8.,   8.,  18.,  31.,  16.,  15.,  10.,  13.,   9.,  32., 161.,
         6.,  20.,   8.,  11.,  13.,   8.,  19.,   7.,   9.,  16.,  11.,
         6.,  38.,  11.,  17.,  13.,  12.,  12.,   9.,   7.,  15.,  14.,
        14.,  11.,  13.,  12.,  12.,  24.,  15.,  38.,  18.,  26.,  15.,
        12.,  14.,  40.,  19.,  13.,  39.,  19.,  16.,  19.,  11.,  76.,
        14.,  19.,  26.,  19.,  17.,  30.,  17.,  17.,  17.,  19.,  11.,
       175.,  10.,   5.,  12.,   7.,  12.,  14.,  19.,  11.,  19.,  17.,
        15.,  19.,  15.,   9.,  20.,   6.,  11.,   6.,  15.,  20.,  35.,
        34.,  21.,  17.,  22.,  26.,  16.,  16.,  28.,  19.,  17.,  15.,
        11.,   7.,  15.,  11.,  36.,  16.,  22.,  18.,  46.,  17.,  15.,
        17.,  12.,  17.,  14.,  15.,  14.,  15.,  28.,  36.,  23.,  12.,
        25.,  18.,  18.,  16.,  20.,  17.,  16.,  13.,  15.,  19.,  14.,
        20.,  37.,  16.,  15.,  11.,  42.,  10.,  14.,  61.,  39.,  17.,
        17.,  41.,  35.,  16.,   9.,  64.,  22.,  22.,  66.,  33.,  30.,
        16.,  18.,  45.,  17.,  88.,  23.,  18.,  12.,  12.,  13.,  13.,
         5.,  11.,  13.,  11.,  22.,  10.,  13.,  17.,  10.,  14.,  18.,
         9.,  16.,  17.,   6.,  15.,  18.,  10.,  11.,  16.,  10.,  12.,
        12.,  13.,   9.,  16.,  19.,  19.,  11.,  15.,  10.,  20.,  25.,
         9.,  14.,  10.,  14.,  18.,  25.,  13.,  24.,  14.,  13.,  14.,
        24.,  16.,  15.,  13.,  11.,  12.,  28.,  28.,  17.,  27.,  48.,
       184.,  64.,  24.,  92.,  31.,  34.,  49.,  21.,  36.,  32.,  16.,
        16.,  19.,  22.,  22.,  19.,  18.,  18.,  17.,  35.,  49.,  19.,
        25.,  24.,  39.,  19.,  29.,  30.,  16.,  54.,  15.,  39.,  19.,
        17.,  60.,  12.,  77.,  63.,  12.,   9.,  34.,  30.,  13.,  20.,
        29.,  10.,  14.,  23.,  15.,  12.,  25.,  22., 144.,  31.,  31.,
        17.,  66.,  78.,  19.,  44.,  43.,  35.,  13.,  13.,  25.,  15.,
        37.,  38.,  22.,  28.,  19.,  46.,  24.,  22.,  43.,  58.,  26.,
        20.,  27.,  35.,  20.,  31.,  24.,  24.,  94.,  18.,  20.,  18.,
        16.,  38.,  54.,  29.,  49.,  25.,  72., 144.,  36.,  97., 179.,
        29.,  12.,  21.,  42.,  53.,  41.,  19.,  25.,  19.,  15.,  21.,
        21.,  27.,  33.,  15.,  24.,  13.,  11.,  14.,  26.,  11.,  21.,
        14.,  14.,  54.,   5.,  10.,  12.,  11.,  14.,  28.,  23.,  20.,
         9.,  12.,  11.,  14.,  14.,  15.,  15.,  11.,  20.,  13.,  19.,
       621.,  57.,  17.,  23.,  19.,  21.,  47.,  28.,  22.,  22.,  65.,
        27.,  17.,  17.,  13.,   9.,  18.,  22.,  17.,  15.,  22.,  23.,
        19.,  17.,  42.,  28.,  15.,   9.,  30.,  52.,  45.,  26.,  20.])

In [14]:
X = row[0:549]
y = row[1:550]

In [15]:
X

array([ 11.,  14.,  15.,  18.,  11.,  13.,  22.,  11.,  10.,   4.,  41.,
        65.,  57.,  38.,  20.,  62.,  44.,  15.,  10.,  47.,  24.,  17.,
        22.,   9.,  39.,  13.,  11.,  12.,  21.,  19.,   9.,  15.,  33.,
         8.,   8.,   7.,  13.,   2.,  23.,  12.,  27.,  27.,  36.,  23.,
        58.,  80.,  60.,  69.,  42., 161.,  94.,  77.,  78.,  20.,  24.,
        13.,  14.,  26.,   8.,  82.,  22.,  11.,  81.,  37.,   9.,  40.,
        47.,  18.,  23.,   6.,   2.,   7.,  16.,  10.,  34.,  14.,  31.,
        20.,  23.,  14.,  16.,  34.,  15.,  30.,  13.,  30.,  15.,  25.,
        17.,   8.,  12.,  17.,  10.,  21.,  18.,  30.,  13.,   7.,  15.,
        23.,  20.,  15.,   9.,  47.,  14.,  11.,  16.,  12.,   7.,  15.,
        14.,  12.,  18.,  29.,  39.,  11.,  14.,  28.,  17.,  20.,  17.,
        36.,  13.,  11.,  14.,  14.,  14.,  33.,  14.,  13.,  18.,  13.,
        11.,   8.,  10.,  11.,  81.,  14.,  20.,   6.,  16.,  18.,   9.,
        12.,  10.,   8.,  11.,  14.,  47.,  13.,  13.,   6.,  10.,   8.,
         8.,   8.,  18.,  31.,  16.,  15.,  10.,  13.,   9.,  32., 161.,
         6.,  20.,   8.,  11.,  13.,   8.,  19.,   7.,   9.,  16.,  11.,
         6.,  38.,  11.,  17.,  13.,  12.,  12.,   9.,   7.,  15.,  14.,
        14.,  11.,  13.,  12.,  12.,  24.,  15.,  38.,  18.,  26.,  15.,
        12.,  14.,  40.,  19.,  13.,  39.,  19.,  16.,  19.,  11.,  76.,
        14.,  19.,  26.,  19.,  17.,  30.,  17.,  17.,  17.,  19.,  11.,
       175.,  10.,   5.,  12.,   7.,  12.,  14.,  19.,  11.,  19.,  17.,
        15.,  19.,  15.,   9.,  20.,   6.,  11.,   6.,  15.,  20.,  35.,
        34.,  21.,  17.,  22.,  26.,  16.,  16.,  28.,  19.,  17.,  15.,
        11.,   7.,  15.,  11.,  36.,  16.,  22.,  18.,  46.,  17.,  15.,
        17.,  12.,  17.,  14.,  15.,  14.,  15.,  28.,  36.,  23.,  12.,
        25.,  18.,  18.,  16.,  20.,  17.,  16.,  13.,  15.,  19.,  14.,
        20.,  37.,  16.,  15.,  11.,  42.,  10.,  14.,  61.,  39.,  17.,
        17.,  41.,  35.,  16.,   9.,  64.,  22.,  22.,  66.,  33.,  30.,
        16.,  18.,  45.,  17.,  88.,  23.,  18.,  12.,  12.,  13.,  13.,
         5.,  11.,  13.,  11.,  22.,  10.,  13.,  17.,  10.,  14.,  18.,
         9.,  16.,  17.,   6.,  15.,  18.,  10.,  11.,  16.,  10.,  12.,
        12.,  13.,   9.,  16.,  19.,  19.,  11.,  15.,  10.,  20.,  25.,
         9.,  14.,  10.,  14.,  18.,  25.,  13.,  24.,  14.,  13.,  14.,
        24.,  16.,  15.,  13.,  11.,  12.,  28.,  28.,  17.,  27.,  48.,
       184.,  64.,  24.,  92.,  31.,  34.,  49.,  21.,  36.,  32.,  16.,
        16.,  19.,  22.,  22.,  19.,  18.,  18.,  17.,  35.,  49.,  19.,
        25.,  24.,  39.,  19.,  29.,  30.,  16.,  54.,  15.,  39.,  19.,
        17.,  60.,  12.,  77.,  63.,  12.,   9.,  34.,  30.,  13.,  20.,
        29.,  10.,  14.,  23.,  15.,  12.,  25.,  22., 144.,  31.,  31.,
        17.,  66.,  78.,  19.,  44.,  43.,  35.,  13.,  13.,  25.,  15.,
        37.,  38.,  22.,  28.,  19.,  46.,  24.,  22.,  43.,  58.,  26.,
        20.,  27.,  35.,  20.,  31.,  24.,  24.,  94.,  18.,  20.,  18.,
        16.,  38.,  54.,  29.,  49.,  25.,  72., 144.,  36.,  97., 179.,
        29.,  12.,  21.,  42.,  53.,  41.,  19.,  25.,  19.,  15.,  21.,
        21.,  27.,  33.,  15.,  24.,  13.,  11.,  14.,  26.,  11.,  21.,
        14.,  14.,  54.,   5.,  10.,  12.,  11.,  14.,  28.,  23.,  20.,
         9.,  12.,  11.,  14.,  14.,  15.,  15.,  11.,  20.,  13.,  19.,
       621.,  57.,  17.,  23.,  19.,  21.,  47.,  28.,  22.,  22.,  65.,
        27.,  17.,  17.,  13.,   9.,  18.,  22.,  17.,  15.,  22.,  23.,
        19.,  17.,  42.,  28.,  15.,   9.,  30.,  52.,  45.,  26.])

In [16]:
y

array([ 14.,  15.,  18.,  11.,  13.,  22.,  11.,  10.,   4.,  41.,  65.,
        57.,  38.,  20.,  62.,  44.,  15.,  10.,  47.,  24.,  17.,  22.,
         9.,  39.,  13.,  11.,  12.,  21.,  19.,   9.,  15.,  33.,   8.,
         8.,   7.,  13.,   2.,  23.,  12.,  27.,  27.,  36.,  23.,  58.,
        80.,  60.,  69.,  42., 161.,  94.,  77.,  78.,  20.,  24.,  13.,
        14.,  26.,   8.,  82.,  22.,  11.,  81.,  37.,   9.,  40.,  47.,
        18.,  23.,   6.,   2.,   7.,  16.,  10.,  34.,  14.,  31.,  20.,
        23.,  14.,  16.,  34.,  15.,  30.,  13.,  30.,  15.,  25.,  17.,
         8.,  12.,  17.,  10.,  21.,  18.,  30.,  13.,   7.,  15.,  23.,
        20.,  15.,   9.,  47.,  14.,  11.,  16.,  12.,   7.,  15.,  14.,
        12.,  18.,  29.,  39.,  11.,  14.,  28.,  17.,  20.,  17.,  36.,
        13.,  11.,  14.,  14.,  14.,  33.,  14.,  13.,  18.,  13.,  11.,
         8.,  10.,  11.,  81.,  14.,  20.,   6.,  16.,  18.,   9.,  12.,
        10.,   8.,  11.,  14.,  47.,  13.,  13.,   6.,  10.,   8.,   8.,
         8.,  18.,  31.,  16.,  15.,  10.,  13.,   9.,  32., 161.,   6.,
        20.,   8.,  11.,  13.,   8.,  19.,   7.,   9.,  16.,  11.,   6.,
        38.,  11.,  17.,  13.,  12.,  12.,   9.,   7.,  15.,  14.,  14.,
        11.,  13.,  12.,  12.,  24.,  15.,  38.,  18.,  26.,  15.,  12.,
        14.,  40.,  19.,  13.,  39.,  19.,  16.,  19.,  11.,  76.,  14.,
        19.,  26.,  19.,  17.,  30.,  17.,  17.,  17.,  19.,  11., 175.,
        10.,   5.,  12.,   7.,  12.,  14.,  19.,  11.,  19.,  17.,  15.,
        19.,  15.,   9.,  20.,   6.,  11.,   6.,  15.,  20.,  35.,  34.,
        21.,  17.,  22.,  26.,  16.,  16.,  28.,  19.,  17.,  15.,  11.,
         7.,  15.,  11.,  36.,  16.,  22.,  18.,  46.,  17.,  15.,  17.,
        12.,  17.,  14.,  15.,  14.,  15.,  28.,  36.,  23.,  12.,  25.,
        18.,  18.,  16.,  20.,  17.,  16.,  13.,  15.,  19.,  14.,  20.,
        37.,  16.,  15.,  11.,  42.,  10.,  14.,  61.,  39.,  17.,  17.,
        41.,  35.,  16.,   9.,  64.,  22.,  22.,  66.,  33.,  30.,  16.,
        18.,  45.,  17.,  88.,  23.,  18.,  12.,  12.,  13.,  13.,   5.,
        11.,  13.,  11.,  22.,  10.,  13.,  17.,  10.,  14.,  18.,   9.,
        16.,  17.,   6.,  15.,  18.,  10.,  11.,  16.,  10.,  12.,  12.,
        13.,   9.,  16.,  19.,  19.,  11.,  15.,  10.,  20.,  25.,   9.,
        14.,  10.,  14.,  18.,  25.,  13.,  24.,  14.,  13.,  14.,  24.,
        16.,  15.,  13.,  11.,  12.,  28.,  28.,  17.,  27.,  48., 184.,
        64.,  24.,  92.,  31.,  34.,  49.,  21.,  36.,  32.,  16.,  16.,
        19.,  22.,  22.,  19.,  18.,  18.,  17.,  35.,  49.,  19.,  25.,
        24.,  39.,  19.,  29.,  30.,  16.,  54.,  15.,  39.,  19.,  17.,
        60.,  12.,  77.,  63.,  12.,   9.,  34.,  30.,  13.,  20.,  29.,
        10.,  14.,  23.,  15.,  12.,  25.,  22., 144.,  31.,  31.,  17.,
        66.,  78.,  19.,  44.,  43.,  35.,  13.,  13.,  25.,  15.,  37.,
        38.,  22.,  28.,  19.,  46.,  24.,  22.,  43.,  58.,  26.,  20.,
        27.,  35.,  20.,  31.,  24.,  24.,  94.,  18.,  20.,  18.,  16.,
        38.,  54.,  29.,  49.,  25.,  72., 144.,  36.,  97., 179.,  29.,
        12.,  21.,  42.,  53.,  41.,  19.,  25.,  19.,  15.,  21.,  21.,
        27.,  33.,  15.,  24.,  13.,  11.,  14.,  26.,  11.,  21.,  14.,
        14.,  54.,   5.,  10.,  12.,  11.,  14.,  28.,  23.,  20.,   9.,
        12.,  11.,  14.,  14.,  15.,  15.,  11.,  20.,  13.,  19., 621.,
        57.,  17.,  23.,  19.,  21.,  47.,  28.,  22.,  22.,  65.,  27.,
        17.,  17.,  13.,   9.,  18.,  22.,  17.,  15.,  22.,  23.,  19.,
        17.,  42.,  28.,  15.,   9.,  30.,  52.,  45.,  26.,  20.])

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

In [18]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
X_train = np.reshape(X_train,(-1,1))
y_train = np.reshape(y_train,(-1,1))
X_train = sc.fit_transform(X_train)
y_train = sc.fit_transform(y_train)

In [19]:
X_train

array([[0.02746365],
       [0.0371567 ],
       [0.03392569],
       [0.04200323],
       [0.01938611],
       [0.02907916],
       [0.04523425],
       [0.13893376],
       [0.01453958],
       [0.04361874],
       [0.01938611],
       [0.00969305],
       [0.02100162],
       [0.12924071],
       [0.0549273 ],
       [0.22940226],
       [0.03069467],
       [0.01130856],
       [0.00646204],
       [0.07108239],
       [0.05815832],
       [0.0177706 ],
       [0.02746365],
       [0.01615509],
       [0.02746365],
       [0.02261712],
       [0.03877221],
       [0.00969305],
       [0.02423263],
       [0.01292407],
       [0.08400646],
       [0.02746365],
       [0.0177706 ],
       [0.12277868],
       [0.05169628],
       [0.01453958],
       [0.01130856],
       [0.01292407],
       [0.00969305],
       [0.01453958],
       [0.04684976],
       [0.01615509],
       [0.02261712],
       [0.0355412 ],
       [0.0177706 ],
       [0.02584814],
       [0.00484653],
       [0.06138934],
       [0.01453958],
       [0.02423263],
       [0.0177706 ],
       [0.03231018],
       [0.03392569],
       [0.02746365],
       [0.0355412 ],
       [0.07592892],
       [0.01453958],
       [0.02907916],
       [0.00969305],
       [0.02423263],
       [0.0177706 ],
       [0.0355412 ],
       [0.27948304],
       [0.0177706 ],
       [0.01130856],
       [0.03069467],
       [0.07108239],
       [0.02423263],
       [0.05169628],
       [0.02100162],
       [0.06946688],
       [0.01615509],
       [0.03231018],
       [0.02100162],
       [0.02423263],
       [0.01292407],
       [0.02746365],
       [0.00646204],
       [0.02746365],
       [0.02100162],
       [0.0549273 ],
       [0.0371567 ],
       [0.04038772],
       [0.12116317],
       [0.02584814],
       [0.01615509],
       [0.01938611],
       [0.01130856],
       [0.01453958],
       [0.25686591],
       [0.02261712],
       [0.15347334],
       [0.05654281],
       [0.01453958],
       [0.01938611],
       [0.02746365],
       [0.08400646],
       [0.05815832],
       [0.03069467],
       [0.01453958],
       [0.00646204],
       [0.01615509],
       [0.00969305],
       [0.0177706 ],
       [0.01615509],
       [0.00484653],
       [1.        ],
       [0.01453958],
       [0.01130856],
       [0.0371567 ],
       [0.02100162],
       [0.01292407],
       [0.02746365],
       [0.01453958],
       [0.05331179],
       [0.01615509],
       [0.05977383],
       [0.0726979 ],
       [0.00646204],
       [0.01453958],
       [0.04684976],
       [0.01453958],
       [0.01292407],
       [0.1276252 ],
       [0.01615509],
       [0.00807754],
       [0.0177706 ],
       [0.02746365],
       [0.02100162],
       [0.01938611],
       [0.02100162],
       [0.02746365],
       [0.00969305],
       [0.00969305],
       [0.02423263],
       [0.01453958],
       [0.0904685 ],
       [0.01453958],
       [0.01938611],
       [0.01453958],
       [0.10177706],
       [0.02100162],
       [0.0549273 ],
       [0.02746365],
       [0.10016155],
       [0.02423263],
       [0.01292407],
       [0.05977383],
       [0.00807754],
       [0.0177706 ],
       [0.02746365],
       [0.04684976],
       [0.02746365],
       [0.01130856],
       [0.02584814],
       [0.03231018],
       [0.02423263],
       [0.01615509],
       [0.01938611],
       [0.02100162],
       [0.02584814],
       [0.02746365],
       [0.12116317],
       [0.02907916],
       [0.02746365],
       [0.01938611],
       [0.04523425],
       [0.01130856],
       [0.02907916],
       [0.02423263],
       [0.02261712],
       [0.0177706 ],
       [0.04523425],
       [0.03392569],
       [0.02746365],
       [0.01130856],
       [0.03231018],
       [0.02584814],
       [0.05977383],
       [0.02423263],
       [0.02261712],
       [0.01615509],
       [0.0177706 ],
       [0.01615509],
       [0.02907916],
       [0.01453958],
       [0.04361874],
       [0.04038772],
       [0.01615509],
       [0.02423263],
       [0.01938611],
       [0.04038772],
       [0.29402262],
       [0.01292407],
       [0.05815832],
       [0.05654281],
       [0.02423263],
       [0.03877221],
       [0.02423263],
       [0.01453958],
       [0.0177706 ],
       [0.0177706 ],
       [0.04523425],
       [0.04200323],
       [0.0177706 ],
       [0.01938611],
       [0.0177706 ],
       [0.01292407],
       [0.06785137],
       [0.08400646],
       [0.02261712],
       [0.02100162],
       [0.0355412 ],
       [0.00646204],
       [0.01453958],
       [0.02584814],
       [0.01130856],
       [0.0371567 ],
       [0.0177706 ],
       [0.03231018],
       [0.0371567 ],
       [0.02261712],
       [0.02584814],
       [0.05815832],
       [0.0726979 ],
       [0.01938611],
       [0.02423263],
       [0.03877221],
       [0.01938611],
       [0.0355412 ],
       [0.01938611],
       [0.02584814],
       [0.02584814],
       [0.05169628],
       [0.01938611],
       [0.02423263],
       [0.02907916],
       [0.02907916],
       [0.00807754],
       [0.02423263],
       [0.02907916],
       [0.03392569],
       [0.0371567 ],
       [0.09531502],
       [0.02423263],
       [0.01615509],
       [0.05008078],
       [0.02261712],
       [0.04523425],
       [0.02261712],
       [0.10177706],
       [0.01938611],
       [0.04200323],
       [0.02100162],
       [0.02423263],
       [0.0177706 ],
       [0.02100162],
       [0.00969305],
       [0.04038772],
       [0.02100162],
       [0.09854604],
       [0.14862682],
       [0.01938611],
       [0.08239095],
       [0.06462036],
       [0.01615509],
       [0.01292407],
       [0.01453958],
       [0.00484653],
       [0.01292407],
       [0.1276252 ],
       [0.02423263],
       [0.1453958 ],
       [0.02584814],
       [0.01938611],
       [0.01130856],
       [0.03231018],
       [0.03069467],
       [0.03392569],
       [0.04200323],
       [0.07592892],
       [0.01453958],
       [0.04846527],
       [0.02746365],
       [0.05977383],
       [0.01615509],
       [0.01453958],
       [0.02100162],
       [0.03231018],
       [0.01292407],
       [0.03231018],
       [0.04361874],
       [0.01292407],
       [0.01453958],
       [0.04200323],
       [0.01453958],
       [0.02584814],
       [0.02100162],
       [0.04523425],
       [0.02584814],
       [0.04846527],
       [0.0177706 ],
       [0.00646204],
       [0.10339257],
       [0.06462036],
       [0.01615509],
       [0.07431341],
       [0.0355412 ],
       [0.01453958],
       [0.02907916],
       [0.02100162],
       [0.02746365],
       [0.0726979 ],
       [0.01615509],
       [0.02100162],
       [0.0177706 ],
       [0.02584814],
       [0.02907916],
       [0.0177706 ],
       [0.05008078],
       [0.1082391 ],
       [0.04038772],
       [0.02423263],
       [0.01292407],
       [0.05977383],
       [0.0177706 ],
       [0.22940226],
       [0.0549273 ],
       [0.04200323],
       [0.08885299],
       [0.01130856],
       [0.05977383],
       [0.02261712],
       [0.02423263],
       [0.02100162],
       [0.10339257],
       [0.01938611],
       [0.02907916],
       [0.0177706 ],
       [0.06462036],
       [0.03877221],
       [0.03231018],
       [0.02100162],
       [0.0177706 ],
       [0.0549273 ],
       [0.0355412 ],
       [0.02100162],
       [0.03231018],
       [0.0549273 ],
       [0.03231018],
       [0.02584814],
       [0.03392569],
       [0.0355412 ],
       [0.02907916],
       [0.03392569],
       [0.01938611],
       [0.03069467],
       [0.01130856],
       [0.02584814],
       [0.01938611],
       [0.00646204],
       [0.02423263],
       [0.01615509],
       [0.02261712],
       [0.01615509],
       [0.01938611],
       [0.05815832],
       [0.03392569],
       [0.06623586],
       [0.12277868],
       [0.01453958],
       [0.02261712],
       [0.03231018],
       [0.02261712],
       [0.0371567 ],
       [0.05008078],
       [0.02584814],
       [0.0371567 ],
       [0.28594507],
       [0.        ],
       [0.02584814],
       [0.00323102],
       [0.0355412 ],
       [0.0355412 ]])

In [20]:
from xgboost import XGBRegressor

In [21]:
xg = XGBRegressor()

In [22]:
xg.fit(X_train, y_train)

[21:54:01] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

XGBRegressor()

In [23]:
X_test = np.reshape(X_test,(-1,1))
X_test = sc.transform(X_test)

In [24]:
y_pred_xg = xg.predict(X_test)

In [25]:
y_pred_xg

array([0.03804687, 0.03679439, 0.02431744, 0.02389228, 0.02884215,
       0.02122611, 0.04086712, 0.02431744, 0.04086712, 0.0290933 ,
       0.0290933 , 0.04331008, 0.03710863, 0.02431744, 0.03804687,
       0.05476904, 0.11318377, 0.06844732, 0.04425213, 0.04425213,
       0.0290933 , 0.08612061, 0.0290933 , 0.02431744, 0.0290933 ,
       0.03679439, 0.06844732, 0.0290933 , 0.02431744, 0.1010069 ,
       0.0285455 , 0.0290933 , 0.03225026, 0.04051834, 0.03804687,
       0.02389228, 0.04168957, 0.04331008, 0.05476904, 0.02431744,
       0.0290933 , 0.03514865, 0.0290933 , 0.04051834, 0.02431744,
       0.0285455 , 0.02884215, 0.04029968, 0.0290933 , 0.032996  ,
       0.06844732, 0.0290933 , 0.03710863, 0.03225026, 0.06844732,
       0.02389228, 0.03407186, 0.03679439, 0.04425213, 0.06844732,
       0.02431744, 0.0290933 , 0.02389228, 0.0285455 , 0.0290933 ,
       0.06361845, 0.032996  , 0.02431744, 0.0290933 , 0.02431744,
       0.0290933 , 0.02431744, 0.03710863, 0.02389228, 0.0290933 ,
       0.1010069 , 0.04115126, 0.03507736, 0.0290933 , 0.0290933 ,
       0.02431744, 0.032996  , 0.0290933 , 0.06844732, 0.0321162 ,
       0.04168957, 0.0290933 , 0.1010069 , 0.03804687, 0.04168957,
       0.04086712, 0.04086712, 0.0290933 , 0.04168957, 0.0290933 ,
       0.0290933 , 0.04425213, 0.0797177 , 0.0290933 , 0.03679439,
       0.03514865, 0.03225026, 0.03710863, 0.0290933 , 0.02431744,
       0.03507736, 0.0290933 , 0.04051834, 0.06844732, 0.04115126,
       0.0290933 , 0.0290933 , 0.03514865, 0.06844732, 0.04086712,
       0.0290933 , 0.0290933 , 0.07572231, 0.04331008, 0.0290933 ,
       0.032996  , 0.03804687, 0.1010069 , 0.03804687, 0.0321162 ,
       0.0290933 , 0.03225026, 0.06361845, 0.0290933 , 0.03407186,
       0.06361845, 0.0290933 , 0.0290933 , 0.04115126, 0.0321162 ,
       0.0321162 , 0.02431744, 0.0290933 , 0.03804687, 0.03225026,
       0.02431744, 0.0290933 , 0.03507736, 0.0290933 , 0.03804687,
       0.0290933 , 0.02389228, 0.03225026, 0.04545042, 0.032996  ,
       0.0290933 , 0.02094564, 0.04086712, 0.02884215, 0.0290933 ,
       0.03225026, 0.0290933 , 0.0290933 , 0.02884215, 0.04331008,
       0.04331008, 0.02884215, 0.0290933 , 0.0290933 , 0.0290933 ],
      dtype=float32)

In [26]:
y_test = np.reshape(y_test,(-1,1))
y_test = sc.transform(y_test)

In [27]:
accuracy = xg.score(X_test, y_test)

In [28]:
accuracy

-0.08119189394474291

In [29]:
from sklearn.metrics import mean_squared_error

rms = mean_squared_error(y_test, y_pred_xg)

In [30]:
rms

0.0013478805130859783

In [31]:
train_n = pd.read_csv('/content/train_1.csv')

In [32]:
train_flattened = pd.melt(train_n[list(train_n.columns[-50:])+['Page']], id_vars='Page', var_name='date', value_name='Visits')
train_flattened['date'] = train_flattened['date'].astype('datetime64[ns]')
train_flattened['weekend'] = ((train_flattened.date.dt.dayofweek) // 5 == 1).astype(float)

In [33]:
df_median = pd.DataFrame(train_flattened.groupby(['Page'])['Visits'].median())
df_median.columns = ['median']

# Average by page
df_mean = pd.DataFrame(train_flattened.groupby(['Page'])['Visits'].mean())
df_mean.columns = ['mean']

# Merging data
train_flattened = train_flattened.set_index('Page').join(df_mean).join(df_median)

In [34]:
train_flattened.reset_index(drop=False,inplace=True)
train_flattened['weekday'] = train_flattened['date'].apply(lambda x: x.weekday())
train_flattened['year']=train_flattened.date.dt.year 
train_flattened['month']=train_flattened.date.dt.month 
train_flattened['day']=train_flattened.date.dt.day

In [35]:
train_flattened

                                                      Page  ... day
0             !vote_en.wikipedia.org_all-access_all-agents  ...  12
1             !vote_en.wikipedia.org_all-access_all-agents  ...  13
2             !vote_en.wikipedia.org_all-access_all-agents  ...  14
3             !vote_en.wikipedia.org_all-access_all-agents  ...  15
4             !vote_en.wikipedia.org_all-access_all-agents  ...  16
...                                                    ...  ...  ..
7253145  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  ...  27
7253146  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  ...  28
7253147  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  ...  29
7253148  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  ...  30
7253149  ［Alexandros］_ja.wikipedia.org_mobile-web_all-a...  ...  31

[7253150 rows x 10 columns]

In [36]:
train_flattened = train_flattened.dropna()

In [37]:
train_flattened = train_flattened[1:100000]

In [38]:
train_flattened.drop(["Page"],axis=1)

             date  Visits  weekend        mean  ...  weekday  year  month  day
1      2016-11-13     2.0      1.0    2.836735  ...        6  2016     11   13
2      2016-11-14     4.0      0.0    2.836735  ...        0  2016     11   14
3      2016-11-15     8.0      0.0    2.836735  ...        1  2016     11   15
4      2016-11-16     3.0      0.0    2.836735  ...        2  2016     11   16
5      2016-11-17     2.0      0.0    2.836735  ...        3  2016     11   17
...           ...     ...      ...         ...  ...      ...   ...    ...  ...
102578 2016-12-10   286.0      1.0  134.600000  ...        5  2016     12   10
102579 2016-12-11   253.0      1.0  134.600000  ...        6  2016     12   11
102580 2016-12-12   227.0      0.0  134.600000  ...        0  2016     12   12
102581 2016-12-13   209.0      0.0  134.600000  ...        1  2016     12   13
102582 2016-12-14   122.0      0.0  134.600000  ...        2  2016     12   14

[99999 rows x 9 columns]

In [39]:
y_n = train_flattened["Visits"]

In [40]:
X_n = train_flattened.drop(["date","Visits","Page"], axis=1)

In [41]:
X_train_n, X_test_n, y_train_n, y_test_n = train_test_split(X_n, y_n, test_size = 0.2, random_state = 0)

In [42]:
X_train_n

        weekend     mean  median  weekday  year  month  day
10686       1.0  2469.30  2264.5        6  2016     12   18
74924       0.0    58.20    46.0        1  2016     12    6
31480       0.0    30.30    26.5        0  2016     12   12
101886      1.0     4.70     4.0        6  2016     12   18
60163       0.0     8.78     8.0        4  2016     11   25
...         ...      ...     ...      ...   ...    ...  ...
21572       1.0    61.02    51.0        6  2016     12    4
46635       1.0    25.80    22.5        5  2016     12   17
43353       0.0    10.90     7.0        1  2016     11   15
44307       1.0     7.26     6.0        5  2016     11   19
69639       0.0     6.12     6.0        2  2016     12   21

[79999 rows x 7 columns]

In [43]:
xg.fit(X_train_n, y_train_n)

[21:54:51] WARNING: /workspace/src/objective/regression_obj.cu:152: reg:linear is now deprecated in favor of reg:squarederror.

XGBRegressor()

In [44]:
y_pred_xg = xg.predict(X_test_n)

In [45]:
y_pred_xg = pd.Series(y_pred_xg)
y_pred_xg

0         43.176311
1        957.399292
2         59.598827
3        704.064941
4         43.176311
            ...
19995    280.897858
19996    583.918579
19997     50.402367
19998    361.727509
19999     29.053007
Length: 20000, dtype: float32

In [46]:
y_test_n

3722      41.0
61702    767.0
54406     48.0
21664    411.0
4025      18.0
         ...
61320    236.0
2555     179.0
44503      4.0
72751     69.0
84670     19.0
Name: Visits, Length: 20000, dtype: float64

In [47]:
rms = mean_squared_error(y_test_n, y_pred_xg)

In [48]:
accuracy = xg.score(X_test_n, y_test_n)

In [49]:
accuracy

0.6509556015526814

In [50]:
from sklearn.linear_model import LogisticRegression

In [51]:
lr = LogisticRegression()

In [ ]:
lr.fit(X_train_n, y_train_n)

In [ ]:
y_pred_lr = lr.predict(X_test_n)

In [ ]:
rms = mean_squared_error(y_test_n, y_pred_lr)

In [ ]:
rms